# Generated by Django 2.1.5 on 2019-01-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.CharField(max_length=10, verbose_name='Data de Criação')),
                ('tipoDespesa', models.CharField(choices=[('', (('RÉMEDIO', 'Rémedio'), ('ROUPAS', 'Roupas'), ('ALIMENTAÇÃO', 'Alimentação'), ('Educação', 'Educação'), ('TRANSPORTE', 'Transporte'), ('OUTROS', 'Outros')))], default=' ', max_length=100, verbose_name='Tipo de despesa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('formaPagamento', models.CharField(choices=[(' ', (('DINHEIRO', 'Dinheiro'), ('CARTÃO DE CRÉDITO', 'Cartão de Crédito'), ('CARTÃO DE DÉBITO', 'Cartão de Débito'), ('CARTÃO CREDIÁRIO', 'Cartão Crediário'), ('CHEQUE', 'Cheque')))], default=' ', max_length=50, verbose_name='Forma de Pagamento')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('quitado', models.BooleanField(verbose_name='Quitado')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ('vencimento', 'formaPagamento'),
            },
        ),
    ]
